routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;


Auth::routes();

/**
 * User
 * */
Route::name('users::')->prefix('users')->group(function () {
    Route::get('{user}/{token}/confirm', 'Auth\\RegisterController@confirm')->name('confirm');
    Route::get('{user}/change/pagination/{variant}', 'UserController@changePagination')->name('changePagination');
});

/**
 * Vendor
 * */
Route::name('vendor.')->prefix('vendor')->group(function () {
    Route::get('/', 'VendorController@index')->name('paginate');
    Route::post('remote/shop/', 'VendorController@remoteShop')->name('remote.shop');
});

/**
 * Admin
 * */
Route::name('admin.')->prefix('admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('dashboard');
    Route::post('/register', 'AdminController@registerUser')->name('registerUser');
    Route::patch('/users/{user_id}', 'AdminController@updateUser')->name('updateUser');
    Route::delete('/users/{user_id}', 'AdminController@deleteUser')->name('deleteUser');
});

/**
 * Product
 * */
Route::name('product.')->group(function () {
    Route::get('/', 'ProductController@product')->name('paginate');

    Route::name('current.')->group(function () {
        Route::get('/price/{product_id}', 'ProductController@selling_price')->name('selling_price');
    });
});

/**
 * This show alert after notification with timeout
 * */
Route::group(['prefix' => 'preview', 'as' => 'preview.'], function (){
    Route::group(['prefix' => 'alert', 'as' => 'alert.'], function () {
        Route::get('/{message}/{time}/{redirect_to?}', 'PreviewController@index')->name('message')
            ->where(['time' => '[0-9]+', 'redirect_to' => '[a-z]+']);;
    });
});

//trigger the scheduler
Route::get('/hshhdyw782qgN3Paammxh29' , function(){
    Artisan::call('schedule:run');
    return 'OK';
});

resources/views/admin/list/user_pagination.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: andrewsachno
 * Date: 2019-04-14
 * Time: 19:26
 */
?>


<div class="table-responsive">
    <table class="table">
        <thead class="thead-dark">
        <tr class="">
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col">Accounts Supplier</th>
            <th scope="col">Accounts Vendor</th>
            <th scope="col-3">Roles</th>
            <th scope="col">Enable</th>
            <th scope="col">Event</th>
        </tr>
        </thead>
        <tbody>
        @foreach($users as $user)
            @include('admin.list.user_row', [$user, $accounts_supplier, $accounts_vendor])
        @endforeach
        </tbody>
    </table>
    {{ $users->links() }}
</div>

resources/views/admin/list/user_row.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: andrewsachno
 * Date: 2019-04-23
 * Time: 13:29
 */
?>

<tr id="user_{{$user->id}}" class=" @if($user->hasRole('admin')) bg-warning
                            @elseif($user->hasRole('supplier')) bg-success
                            @elseif($user->hasRole('vendor')) bg-info
                            @endif" data-user="{{$user->id}}" data-href="{{route('admin.updateUser', [$user->id])}}">
    <td>{{$user->id}}</td>
    <td>{{$user->name}}</td>
    <td>{{$user->email}}</td>

    <td>
        <select class="rounded-0 custom-select js-select2 form-control"
                name="accounts_supplier[]"
                multiple="multiple" id="accounts_supplier_{{$user->id}}">
            @foreach($accounts_supplier as $account)
                <option value="{{$account->user_id }}"
                        @if(!empty($user->setting) && in_array($account->user_id, $user->setting->accounts_supplier))  selected @endif >
                    {{$account->display_name }}
                </option>
            @endforeach
        </select>
        <span class="invalid-feedback" role="alert"><strong></strong></span>
    </td>

    <td>
        <select class="rounded-0 custom-select js-select2 form-control"
                name="accounts_vendor[]"
                multiple="multiple" id="accounts_vendor_{{$user->id}}">
            @foreach($accounts_vendor as $account)
                <option value="{{$account->user_id }}"
                        @if(!empty($user->setting) && in_array($account->user_id, $user->setting->accounts_vendor)) selected @endif >
                    {{$account->display_name }}
                </option>
            @endforeach
        </select>
        <span class="invalid-feedback" role="alert"><strong></strong></span>
    </td>

    <td >
        <select class="rounded-0 custom-select js-select2 form-control"
                name="roles[]"
                multiple="multiple" id="roles_{{$user->id}}">
            @foreach(\App\Role::available_roles as $role)
                <option value="{{$role}}"
                        @if(!empty($user->roles) && $user->roles->contains('name', $role)) selected @endif >
                    {{ucfirst($role) }}
                </option>
            @endforeach
        </select>
        <span class="invalid-feedback" role="alert"><strong></strong></span>
    </td>

    <td>
        <input type="checkbox" name="user_verified" @if(!empty($user->user_verified_at)) checked @endif data-toggle="toggle" data-size="sm">
    </td>

    <td>

        <div class="btn-group-vertical btn-group-toggle" data-toggle="buttons">
            <a class="btn bg-danger text-white border border-secondary btn-sm  rounded-0 delete-user-submit"
               href="{{route('admin.deleteUser', [$user->id])}}"
               data-user="{{$user->id}}">{{ __('Delete') }}</a>
        </div>
    </td>
</tr>