routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;


Auth::routes();

/**
 * User
 * */
Route::name('users::')->prefix('users')->group(function () {
    Route::get('{user}/{token}/confirm', 'Auth\\RegisterController@confirm')->name('confirm');
    Route::get('{user}/change/pagination/{variant}', 'UserController@changePagination')->name('changePagination');
});

/**
 * Vendor
 * */
Route::name('vendor.')->prefix('vendor')->group(function () {
    Route::get('/', 'VendorController@index')->name('paginate');
    Route::post('remote/shop/', 'VendorController@remoteShop')->name('remote.shop');
});

/**
 * Admin
 * */
Route::name('admin.')->prefix('admin')->group(function () {
    Route::get('/', 'AdminController@index')->name('dashboard');
    Route::post('/register', 'AdminController@registerUser')->name('registerUser');
    Route::patch('/users/{user_id}', 'AdminController@updateUser')->name('updateUser');
    Route::delete('/users/{user_id}', 'AdminController@deleteUser')->name('deleteUser');
});

/**
 * Product
 * */
Route::name('product.')->group(function () {
    Route::get('/', 'ProductController@product')->name('paginate');

    Route::name('current.')->group(function () {
        Route::get('/price/{product_id}', 'ProductController@selling_price')->name('selling_price');
    });
});

/**
 * This show alert after notification with timeout
 * */
Route::group(['prefix' => 'preview', 'as' => 'preview.'], function (){
    Route::group(['prefix' => 'alert', 'as' => 'alert.'], function () {
        Route::get('/{message}/{time}/{redirect_to?}', 'PreviewController@index')->name('message')
            ->where(['time' => '[0-9]+', 'redirect_to' => '[a-z]+']);;
    });
});

//trigger the scheduler
Route::get('/hshhdyw782qgN3Paammxh29' , function(){
    Artisan::call('schedule:run');
    return 'OK';
});

resources/views/product/list/table/container.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: andrewsachno
 * Date: 2019-05-29
 * Time: 12:09
 */
?>

{{-- hrader pagination for products --}}
{{ $products->links() }}
<div class="table-responsive">
    <table class="table table-striped table-hover table-sm">
        <thead class="thead-dark">
        <tr>
            <th class="text-center" cope="col">#ID</th>
            <th class="text-center" cope="col">Image</th>
            <th class="text-center" cope="col">Name</th>
            <th class="text-center" cope="col">Code</th>
            <th class="text-center" cope="col">Brand</th>
            <th class="text-center" cope="col">Category</th>
            <th class="text-center" cope="col">Q.ty</th>
            @if(Auth::user()->hasAnyRole(['admin', 'supplier']))
                <th class="text-center" cope="col">Supplier</th>
                <th class="text-center" cope="col">Reference</th>
            @endif
        </tr>
        </thead>
        <tbody>
        @foreach ($products as $product)
            @include('product.list.table.item', ['product'=>$product])
        @endforeach
        </tbody>
    </table>
</div>
{{-- footer pagination for products --}}
{{ $products->links() }}

resources/views/product/list/table/item.blade.php
<?php
/**
 * Created by PhpStorm.
 * User: andrewsachno
 * Date: 2019-05-29
 * Time: 12:09
 */
?>

@php
    /*
    IT IS NOT GOOD IDEA. BUT IT'S TEMPORARY SOLUTION. BECAUSE MANY PICTURE NOT IN GOOGLE DRIVE
    */


    $imgs = !empty($product->{'product.images'}) ? json_decode($product->{'product.images'}) : [];

    foreach ($imgs as $key=>$img){
        if(!empty($img) && stristr($img->url, 'google') === false) {
                if (($product->{'supplier.id'} == 1)) {
                    $url_arr = explode("/", $img->url);
                    $image_name = $url_arr[2];
                    $img->url = "https://www.brandsdistribution.com/prod" . '/' . $image_name;
                }
                elseif (strpos($img->url, 'www.dropbox.com') !== false) {
                    $img->url = str_replace('dl=0', 'raw=1', $img->url);
                }
                $imgs[$key] = $img;
        }
    }
@endphp

<tr class="@if($product->{'product.active'} || empty($imgs)) table-danger text-white @endif">
    <td class="text-center" scope="row">
        {{$product->{'product.id'} }}
    </td>
    <td class="" scope="row">
        <div id="carouselExampleControls_{{ $product->{'product.id'} }}" class="carousel slide"
             style="max-width: 100px;"
             data-ride="carousel" data-interval="false">
            <div class="carousel-inner thumbnail">
                @if(empty($imgs))
                    <div class="carousel-item active">
                        <img class="d-block" src="{{url('img/empty_img.jpg')}}" style="max-width: 100px;"
                             onerror="this.onerror=null; this.src='{{  url('img/empty_img.jpg')  }}';"
                             alt="Card image cap">
                    </div>
                @endif
                @foreach($imgs as $key=>$img)
                    <div class="carousel-item @if($key <1) active @endif">
                        <img class="d-block" src="{{$img->url}}" style="max-width: 100px;"
                             onerror="this.onerror=null; this.src='{{  url('img/empty_img.jpg')  }}';"
                             alt="Card image cap">
                    </div>
                @endforeach
            </div>
            @if(count($imgs) > 1)

                <a class="carousel-control-prev" href="#carouselExampleControls_{{ $product->{'product.id'} }}"
                   role="button"
                   data-slide="prev">
                    <span class="carousel-control-prev-icon text-light bg-dark rounded-circle"
                          aria-hidden="true"></span>
                    <span class="sr-only text-light bg-dark">Previous</span>
                </a>
                <a class="carousel-control-next " href="#carouselExampleControls_{{ $product->{'product.id'} }}"
                   role="button"
                   data-slide="next">
                    <span class="carousel-control-next-icon text-light bg-dark rounded-circle"
                          aria-hidden="true"></span>
                    <span class="sr-only text-light bg-dark">Next</span>
                </a>
            @endif
        </div>
    </td>
    <td class="text-center" scope="row">
        {{ $product->{'product.name'} }}
        <br/>
        <a class="btn btn-info btn-sm text-white card-link show-price"
           href="{{route('product.current.selling_price', [ $product->{'product.id'} ])}}" data-toggle="modal"
           data-target="#modal_1">price</a>
    </td>
    <td class="text-center" scope="row">
        {{ $product->{'product.code'} }}
    </td>
    <td class="text-center" scope="row">
        {{ $product->{'product.brand'} }}
    </td>
    <td class="text-center" scope="row">
        {{ $product->{'category.name'} }}
    </td>
    <td class="text-center" scope="row">
        <span class="badge badge-primary "> {{ $product->{'product.availability'} }} </span>
    </td>
    @if(Auth::user()->hasAnyRole(['admin', 'supplier']))
        <td class="text-center" scope="row">
            {{ $product->{'supplier.name'} }}
        </td>
        <td class="text-center" scope="row">
            {{ $product->{'product.unique_id'} }}
        </td>
    @endif
</tr>